#!/home/thatguy/My-repos/Python/github-search-cli-tool/bin/python3
from requests import get 
import webbrowser
import json
import sys
import subprocess
BASE_URL = 'https://api.github.com/users/SpyrosGeo'

webbrowser.register('chrome',None,webbrowser.BackgroundBrowser("/usr/bin/google-chrome"))

repos = get(f"{BASE_URL}/repos?per_page=1000").text

repos = json.loads(repos)
for repo in repos:
    if str(sys.argv[1]) in repo['name'].lower():
        webbrowser.get('chrome').open(repo['html_url'])